volumes:
  db-data:

networks:
  casse-network:
    driver: bridge

services:
  casse-db:
    build:
      context: ./db
    container_name: casse-db
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "dba"
      POSTGRES_PASSWORD: "smit2003"
    networks:
      - casse-network

  redis-casse:
    image: redis
    container_name: redis-casse
    expose:
      - 6379
    command: redis-server --save 60 1 --loglevel warning --requirepass redis123
    networks:
      - casse-network

  casse-daemon:
    image: smitbutle/casse-daemon
    container_name: casse-daemon
    expose:
      - 1929
    environment:
      - SCHEDULER_USERNAME=clockwerk
      - SCHEDULER_PASSWORD=password
      - REDIS_HOST=redis-casse
      - REDIS_PORT=6379
      - REDIS_PASS=redis123
    depends_on:
      - casse-db
      - redis-casse
    networks:
      - casse-network

  casse-ui:
    build:
      context: ./admin-ui
    container_name: casse-ui
    ports:
      - "1930:1930"
    environment:
      - REACT_APP_SCHEDULER_HOST=localhost
      - REACT_APP_SCHEDULER_PORT=1929
      - REACT_APP_SCHEDULER_USERNAME=clockwerk
      - REACT_APP_SCHEDULER_PASSWORD=password
    depends_on:
      - casse-daemon
    networks:
      - casse-network

  
  server:
    build:
      context: ./api
    container_name: casse-server
    ports:
      - "8001:8000"
    env_file:
      - ./api/.env
    depends_on:
      - casse-daemon
    networks:
      - casse-network